In [14]:
#question 1
import numpy as np
arr=np.arange(2,51,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


In [13]:
#question 2
import numpy as np
print("enter first list")
l=[int(input()) for i in range (5)]
print("enter second list")
m=[int(input()) for i in range (5)]
print(l)
print(m)
arr1=np.array(l)
print("first array \n",arr1)
arr2=np.array(m)
print("second array \n",arr2)
arr3=np.concatenate((arr1,arr2))
print("cpncatenate array",arr3)
print("Sorted arrays")
print(np.sort(arr3))

enter first list
1
2
3
4
5
enter second list
1
2
3
4
5
[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
first array 
 [1 2 3 4 5]
second array 
 [1 2 3 4 5]
cpncatenate array [1 2 3 4 5 1 2 3 4 5]
Sorted arrays
[1 1 2 2 3 3 4 4 5 5]


In [8]:
#question 3
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print("dimension of array",arr.ndim)
print("size of array",arr.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
dimension of array 2
size of array 9


In [12]:
#question 4
arr=np.random.rand(5,)
print(arr.ndim)
y=np.expand_dims(arr, axis=0) #with np.expand_dins
print(y)
print(y.ndim)
x=arr[np.newaxis, :]#with np.newaxis adding new axis at start change dim from 2 to 3
print(x)
print(x.ndim)


1
[[0.834217   0.30495726 0.67563282 0.36489424 0.84175739]]
2
[[0.834217   0.30495726 0.67563282 0.36489424 0.84175739]]
2


In [6]:
#question 5
import numpy as np
f=np.random.rand(2,2)
r=np.random.rand(2,2)
print(np.vstack((f,r)))#vertical stack
print()
print(np.hstack((f,r)))#horizontal stack

[[0.91804014 0.40547095]
 [0.31605036 0.44638811]
 [0.635128   0.76545076]
 [0.74660641 0.3179813 ]]

[[0.91804014 0.40547095 0.635128   0.76545076]
 [0.31605036 0.44638811 0.74660641 0.3179813 ]]


In [11]:
#Question 6
arr=np.array([1,2,3,4,5,6,7,8,9,1,2,3,4,5])
print(arr)
print(np.unique(arr))#this shows unique items
print(np.unique(arr,return_counts=True))#this shows items and count of them

[1 2 3 4 5 6 7 8 9 1 2 3 4 5]
[1 2 3 4 5 6 7 8 9]
(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([2, 2, 2, 2, 2, 1, 1, 1, 1], dtype=int64))
